# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mkrrmvBqmbFndNqcvI0FMjMTqd6rDH4B
"""

from datetime import date

class Person:
    def __init__(self, firstName, lastName, dateOfBirth, gender, emiratesID):
        self.firstName = firstName
        self.lastName = lastName
        self.dateOfBirth = dateOfBirth
        self.gender = gender
        self.emiratesID = emiratesID

    def __str__(self):

        dob_str = self.dateOfBirth.strftime("%Y-%m-%d")
        return f"Name: {self.firstName} {self.lastName}, Date of Birth: {dob_str}, Gender: {self.gender}, Emirates ID: {self.emiratesID}"


person = Person("Abdulla", "Ibrahim", date(2003, 2, 7), "Male", "784-2003-789")
print(person)